local o = vim.opt
o.termguicolors = true;
o.backspace = { "indent", "eol", "start" }
o.clipboard = "unnamedplus"
o.errorbells = false;
o.smartcase = true
o.showmode = false
o.swapfile = false
o.backup = false
o.undodir = vim.fn.stdpath('config') .. '/undodir'
o.undofile = true
o.incsearch = true
o.hidden = true
o.completeopt='menuone,noinsert,noselect'
o.autoindent = true
o.smartindent = true
o.paste = true
o.number = true;
o.tabstop = 4;
o.softtabstop = 4;
o.shiftwidth = 4;
o.cc = '80';
